name: Node.js CI

on: push

jobs:
  build:  
    strategy:
      matrix:
        node-version: [10.19.0, 12.16.1]
        os: [ubuntu-16.04, ubuntu-18.04, windows-2019, macos-10.15]
    
    name: Build ${{ matrix.os }} | Node v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run pkg
